void(function(){
   let owo=document.getElementsByTagName("img");
   let hue=document.getElementsByTagName("div");
   let ohno=document.getElementsByTagName("span");
   let uwu=[
  "parrots/hd/parrot.gif",
  "parrots/hd/middleparrot.gif",
  "parrots/hd/reverseparrot.gif",
  "parrots/hd/opensourceparrot.gif",
  "parrots/hd/aussieparrot.gif",
  "parrots/hd/gothparrot.gif",
  "parrots/oldtimeyparrot.gif",
  "parrots/hd/boredparrot.gif",
  "parrots/hd/shuffleparrot.gif",
  "parrots/shufflefurtherparrot.gif",
  "parrots/hd/congaparrot.gif",
  "parrots/hd/reversecongaparrot.gif",
  "parrots/hd/partyparrot.gif",
  "parrots/hd/sadparrot.gif",
  "parrots/hd/copparrot.gif",
  "parrots/hd/fastparrot.gif",
  "parrots/hd/ultrafastparrot.gif",
  "parrots/hd/slowparrot.gif",
  "parrots/slomoparrot.gif",
  "parrots/hd/dadparrot.gif",
  "parrots/hd/dealwithitparrot.gif",
  "parrots/hd/dealwithitnowparrot.gif",
  "parrots/fiestaparrot.gif",
  "parrots/pizzaparrot.gif",
  "parrots/hamburgerparrot.gif",
  "parrots/bananaparrot.gif",
  "parrots/chillparrot.gif",
  "parrots/explodyparrot.gif",
  "parrots/shufflepartyparrot.gif",
  "parrots/icecreamparrot.gif",
  "parrots/hd/sassyparrot.gif",
  "parrots/hd/confusedparrot.gif",
  "parrots/hd/aussiecongaparrot.gif",
  "parrots/hd/aussiereversecongaparrot.gif",
  "parrots/wave1parrot.gif",
  "parrots/wave2parrot.gif",
  "parrots/wave3parrot.gif",
  "parrots/wave4parrot.gif",
  "parrots/wave5parrot.gif",
  "parrots/wave6parrot.gif",
  "parrots/wave7parrot.gif",
  "parrots/wave8parrot.gif",
  "parrots/wave9parrot.gif",
  "parrots/hd/congapartyparrot.gif",
  "parrots/hd/moonwalkingparrot.gif",
  "parrots/hd/thumbsupparrot.gif",
  "parrots/coffeeparrot.gif",
  "parrots/hd/mustacheparrot.gif",
  "parrots/hd/christmasparrot.gif",
  "parrots/hd/sleepingparrot.gif",
  "parrots/hd/beerparrot.gif",
  "parrots/darkbeerparrot.gif",
  "parrots/blondesassyparrot.gif",
  "parrots/bluescluesparrot.gif",
  "parrots/hd/gentlemanparrot.gif",
  "parrots/margaritaparrot.gif",
  "parrots/dreidelparrot.gif",
  "parrots/harrypotterparrot.gif",
  "parrots/upvoteparrot.gif",
  "parrots/hd/twinsparrot.gif",
  "parrots/tripletsparrot.gif",
  "parrots/hd/stableparrot.gif",
  "parrots/shipitparrot.gif",
  "parrots/skiparrot.gif",
  "parrots/loveparrot.gif",
  "parrots/halalparrot.gif",
  "parrots/hd/wendyparrot.gif",
  "parrots/hd/popcornparrot.gif",
  "parrots/hd/donutparrot.gif",
  "parrots/hd/evilparrot.gif",
  "parrots/hd/discoparrot.gif",
  "parrots/matrixparrot.gif",
  "parrots/papalparrot.gif",
  "parrots/stalkerparrot.gif",
  "parrots/hd/scienceparrot.gif",
  "parrots/hd/revolutionparrot.gif",
  "parrots/fidgetparrot.gif",
  "parrots/hd/beretparrot.gif",
  "parrots/tacoparrot.gif",
  "parrots/ryangoslingparrot.gif",
  "parrots/luckyparrot.gif",
  "parrots/hd/birthdaypartyparrot.gif",
  "parrots/hd/jediparrot.gif",
  "parrots/hd/sithparrot.gif",
  "parrots/hd/angryparrot.gif",
  "parrots/hd/invisibleparrot.gif",
  "parrots/fadingparrot.gif",
  "parrots/rotatingparrot.gif",
  "parrots/cryptoparrot.gif",
  "parrots/hd/sushiparrot.gif",
  "parrots/hd/pumpkinparrot.gif",
  "parrots/hd/angelparrot.gif",
  "parrots/hd/bluntparrot.gif",
  "parrots/hd/sintparrot.gif",
  "parrots/hd/pirateparrot.gif",
  "parrots/hd/ceilingparrot.gif",
  "parrots/hd/mardigrasparrot.gif",
  "parrots/sovjetparrot.gif",
  "parrots/portalparrot.gif",
  "parrots/hd/hardhatparrot.gif",
  "parrots/hd/flyingmoneyparrot.gif",
  "parrots/hd/portalorangeparrot.gif",
  "parrots/hd/portalblueparrot.gif",
  "parrots/hd/reverseportalorangeparrot.gif",
  "parrots/hd/reverseportalblueparrot.gif",
  "parrots/hd/bunnyparrot.gif",
  "parrots/hd/norwegianblueparrot.gif",
  "parrots/hd/transparront.gif",
  "parrots/fixparrot.gif",
  "parrots/hd/spyparrot.gif",
  "parrots/hd/marshmallowparrot.gif",
  "parrots/hd/whitewalkerparrot.gif",
  "parrots/hd/calvinist_parrot.gif",
  "parrots/hd/frenchparrot.gif",
  "parrots/hd/githubparrot.gif",
  "parrots/hd/bootlegparrot.gif",
  "parrots/hd/bikerparrot.gif",
  "parrots/hd/inverseparrot.gif",
  "parrots/hd/pingpongparrot.gif",
  "parrots/hd/laptop_parrot.gif",
  "parrots/hd/60fpsparrot.gif",
  "parrots/hd/redhatparrot.gif",
  "parrots/hd/footballparrot.gif",
  "parrots/hd/flowerparrot.gif",
  "parrots/hd/parrotnotfound.gif",
  "parrots/hd/spinningparrot.gif",
  "parrots/hd/redenvelopeparrot.gif",
  "parrots/hd/grouchoparrot.gif",
  "parrots/hd/chicoparrot.gif",
  "parrots/hd/harpoparrot.gif",
  "parrots/schnitzelparrot.gif",
  "parrots/hd/vikingparrot.gif",
  "parrots/hd/darkmodeparrot.gif",
  "parrots/hd/tiedyeparrot.gif",
  "parrots/hd/horizontalparrot.gif",
  "parrots/hd/sherlockholmesparrot.gif",
  "parrots/hd/tennisparrot.gif",
  "parrots/hd/originalparrot.gif",
  "parrots/hd/bobaparrot.gif",
  "parrots/hd/backwardsparrot.gif",
  "parrots/ripparrot.gif",
  "guests/nyanparrot.gif",
  "guests/oriolesparrot.gif",
  "guests/hd/capsparrot.gif",
  "guests/fieriparrot.gif",
  "guests/hd/witnessprotectionparrot.gif",
  "guests/hd/party-wizard.gif",
  "guests/partyowl.gif",
  "guests/hd/parrotpoop.gif",
  "guests/catparrot.gif",
  "guests/hd/trollparrot.gif",
  "guests/hd/dogeparrot.gif",
  "guests/congadoge.gif",
  "guests/hd/partygopher.gif",
  "guests/hd/stubparrot.gif",
  "guests/hd/party-k8s.gif",
  "guests/hd/partycage.gif",
  "guests/hd/batparrot.gif",
  "guests/hd/partysloth.gif",
  "guests/hd/partyblob.gif",
  "guests/hd/partygritty.gif",
  "guests/hd/cryingjordanparrot.gif",
  "guests/hd/partykeanu.gif",
  "guests/hd/partygeeko.gif",
  "https://bit.ly/2RqrUoL",
  "parrots/aussieparrot.gif",
  "parrots/gothparrot.gif",
  "parrots/boredparrot.gif",
  "parrots/reversecongaparrot.gif",
  "parrots/slowparrot.gif",
  "parrots/sassyparrot.gif",
  "parrots/confusedparrot.gif",
  "parrots/aussiecongaparrot.gif",
  "parrots/aussiereversecongaparrot.gif",
  "parrots/moonwalkingparrot.gif",
  "parrots/thumbsupparrot.gif",
  "parrots/parrotbeer.gif",
  "parrots/twinsparrot.gif",
  "parrots/stableparrot.gif",
  "parrots/angryparrot.gif",
  "parrots/brazilianplayerparrot.gif",
  "parrots/brazilianfanparrot.gif",
  "guests/witnessprotectionparrot.gif",
  "guests/dogeparrot.gif"
];
   let lien;
   Array.from(owo).forEach( (e)=>{
       lien = uwu[Math.floor(Math.random()*999)%uwu.length];
       if (lien.includes(".gif")){
         lien = "https://cultofthepartyparrot.com/" + lien
       }
       e.src=lien;e.alt=lien
       console.log("image ◘í╓▐‼∟bÞ☼ed.");
   });
   Array.from(hue).forEach( (e)=>{
     lien = uwu[Math.floor(Math.random()*999)%uwu.length];
     if (lien.includes(".gif")){
         lien = "https://cultofthepartyparrot.com/" + lien
      }
     e.style.backgroundImage = `url(${lien})`
     console.log("a ah ß®∂ç†ƒ√©¥∫˙");
   })
   Array.from(ohno).forEach( (e)=>{
     lien = uwu[Math.floor(Math.random()*999)%uwu.length];
     if (lien.includes(".gif")){
         lien = "https://cultofthepartyparrot.com/" + lien
      }
     e.style.backgroundImage = `url(${lien})`
     console.log("a ah ß®∂ç†ƒ√©¥∫˙");
   })
})();
